### ISSUE TITLE
requirements.txt dependency issues

### ISSUE THREAD

**Issue by cyberbabyangel404** [Joshbazz/polymarket_copy_trader#1] opened 2024-09-26 00:38 UTC
Upon running pip install -r requirements.txt I see an error message regarding a version conflict: The user requested eth-account==0.11.2
    py-clob-client 0.17.5 depends on eth-account>=0.13.0, and upon trying to resolve this via upgrading to eth-account>=0.13.0 another conflict was created with Web3 - I went down a rabbit hole testing various versions and even put it through chatGPT and it told me the following:
    Unfortunately, even the latest versions of web3 have strict requirements for eth-account. As of web3==6.20.2, the dependency specification for eth-account is <0.13 and >=0.8.0, which does not align with the needs of py-clob-client and py-order-utils, both of which require eth-account>=0.13.0. This limitation suggests that, at least for now, the official web3 library is not yet compatible with eth-account versions >=0.13.0.
    
    Any idea how to resolve this?

**Comment by Joshbazz** [comment] 2024-10-01 13:14
Are you operating within a python virtual environment? It is probably best to completely replicate the environment, by using the python version utilized for the project as a whole, you may be able to circumvent these issues

**Comment by rogermas05** [comment] 2024-11-14 10:32
> Are you operating within a python virtual environment? It is probably best to completely replicate the environment, by using the python version utilized for the project as a whole, you may be able to circumvent these issues

Any idea of how to solve this problem? I'm getting the same error

**Comment by Joshbazz** [comment] 2024-11-29 21:24
This may be an issue with the virtual environment setup. When created, my environment was set up using Anaconda. If you are experiencing issues using Venv, it may be beneficial to use Anaconda to setup a Conda virtual environment. Other than that, I am unsure. I would also ask if you are using a linux-based machine versus Windows. This was made on MacOS, and I am unfamiliar with whether it will work as intended on Windows. Other users have reported it working for them

**Comment by rogermas05** [comment] 2024-12-01 02:18
This works now. Have you by any chance tried or experimented with setting up the program as a serverless function (i.e firebase functions, aws lambda or fly.io). I've been trying to get it to work, however I keep running into a 403 Cloudflare issue everytime. Let me know if you have any knowledge on this. Thanks

**Comment by Joshbazz** [comment] 2024-12-01 15:07
I have not, but the issue you're most likely running into is that polymarket is not usable from the United States. So you'd most likely have to use a VPN or a server located outside the United States

**Comment by lexciobotariu** [comment] 2024-12-01 17:33
I created an environment using `conda create -n myenv python=3.10` but I get a similar error saying about a conflict

```
INFO: pip is looking at multiple versions of py-clob-client to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 79) and eth-account==0.11.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested eth-account==0.11.2
    py-clob-client 0.17.5 depends on eth-account>=0.13.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

I'm on windows, did anyone manage to find a solution for this?

**Comment by Joshbazz** [comment] 2024-12-01 17:36
in requirements.txt, replace eth-account==0.11.2 with eth-account>=0.13.0 or eth-account==0.13.0 and retry. Again, this was created and tested on Mac/Linux and I do not know if it will work with Windows

**Comment by lexciobotariu** [comment] 2024-12-01 20:22
I solved the problem by updating the following
```
eth-account>=0.13.0
web3>=6.0.0,<6.20.0

#add this too
setuptools>=65.5.1
```
Also, if you're on Windows you need the [Microsoft Visual C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/) with Desktop development with C++ and select the following extra:
- MSVC v14.x (latest version) (required for Python packages).
- Windows 10 SDK (or later, depending on your system).
- C++ CMake tools for Windows (optional but helpful for building other Python packages).

**Comment by Joshbazz** [comment] 2024-12-01 20:28
Great! Thank you. Im going to close this issue and link it for others to see

**Closed as completed** 2024-12-01 20:28 UTC
Labels: bug

**Comment by rogermas05** [comment] 2024-12-01 23:34
> I have not, but the issue you're most likely running into is that polymarket is not usable from the United States. So you'd most likely have to use a VPN or a server located outside the United States

I'm hosting the program on a server outside the US, so that shouldn't be the issue, however I keep running into the 403 Cloudflare error. It might be that the servers are auto-blocked by Cloudflare, however it's strange that all the different countries are like that. Anyways ....

**Comment by Joshbazz** [comment] 2024-12-04 00:49
Yes not sure what I can do there, but it most likely is something related to Cloudflare or the server implementation you're running. I'd imagine that they have some heavy duty security measures which are firewalling you
